# Generated by Django 5.0.4 on 2024-04-25 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='fecha_de_contrato',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 21, 9, 17, 779675, tzinfo=datetime.timezone.utc)),
        ),
    ]
