# Generated by Django 5.0.4 on 2024-04-25 21:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0002_alter_imagenes_fecha_de_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='diasdetrasmiciones',
            old_name='imagenID',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='imagenes',
            old_name='auth_userID',
            new_name='auth_user',
        ),
        migrations.RenameField(
            model_name='recuperarcontraseña',
            old_name='auth_userID',
            new_name='auth_user',
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='fecha_de_contrato',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 25, 21, 17, 4, 945422, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DatosUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('sector', models.TextField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MiPerfilUsuario',
        ),
    ]
