# Generated by Django 5.0.4 on 2024-07-10 02:12

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0003_rename_imagenid_diasdetrasmiciones_imagen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='fecha_de_contrato',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 2, 12, 14, 211061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sector', models.TextField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_comprobante', models.ImageField(upload_to='mavi/static/img/captures_comprobantes')),
                ('numero_de_referencia', models.CharField(max_length=50)),
                ('dia_de_envio', models.DateTimeField(default=datetime.datetime(2024, 7, 10, 2, 12, 14, 212062, tzinfo=datetime.timezone.utc))),
                ('imagenesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mavi.imagenes')),
            ],
        ),
        migrations.DeleteModel(
            name='DatosUsuarios',
        ),
    ]
