# Generated by Django 5.0.4 on 2024-07-17 22:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0004_alter_imagenes_fecha_de_contrato_datauser_pagos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecuperarContraseña',
            new_name='PasswordRecovery',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='imagenesID',
        ),
        migrations.RenameField(
            model_name='passwordrecovery',
            old_name='codigo',
            new_name='code',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 30, 5, 241616, tzinfo=datetime.timezone.utc))),
                ('image', models.ImageField(upload_to='mavi/static/img')),
                ('review_result', models.BooleanField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_capture', models.ImageField(upload_to='mavi/static/img/captures_comprobantes')),
                ('reference_number', models.CharField(max_length=50)),
                ('sending_day', models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 30, 5, 242650, tzinfo=datetime.timezone.utc))),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mavi.image')),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_day', models.DateField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mavi.image')),
            ],
        ),
        migrations.DeleteModel(
            name='DiasDeTrasmiciones',
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
