# Generated by Django 5.0.4 on 2024-07-17 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0005_rename_recuperarcontraseña_passwordrecovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 33, 43, 453317, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 33, 43, 455308, tzinfo=datetime.timezone.utc)),
        ),
    ]
