# Generated by Django 5.0.4 on 2024-07-17 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0006_image_delete_alter_image_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 33, 47, 631281, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 33, 47, 632278, tzinfo=datetime.timezone.utc)),
        ),
    ]
