# Generated by Django 5.0.4 on 2024-07-18 01:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0007_alter_image_contract_date_alter_payment_sending_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='transmissionday',
            name='image_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 1, 0, 41, 107530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateTimeField(default=datetime.datetime(2024, 7, 18, 1, 0, 41, 105541, tzinfo=datetime.timezone.utc))),
                ('publicity', models.ImageField(upload_to='mavi/static/img')),
                ('review_result', models.BooleanField()),
                ('delete', models.BooleanField(default=False)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='publicity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mavi.publicity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissionday',
            name='publicity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mavi.publicity'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
