# Generated by Django 5.0.4 on 2024-07-18 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0008_remove_payment_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 1, 7, 52, 244243, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 1, 7, 52, 243243, tzinfo=datetime.timezone.utc)),
        ),
    ]
