# Generated by Django 5.0.4 on 2024-07-18 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0009_alter_payment_sending_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicity',
            old_name='delete',
            new_name='removed',
        ),
        migrations.AddField(
            model_name='publicity',
            name='days_transmit',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicity',
            name='publicity_name',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 48, 50, 574023, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 18, 22, 48, 50, 572023, tzinfo=datetime.timezone.utc)),
        ),
    ]
