# Generated by Django 5.0.4 on 2024-07-19 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0010_rename_delete_publicity_removed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='receipt_capture',
            new_name='payment_proof',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 5, 2, 38, 672363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 5, 2, 38, 665637, tzinfo=datetime.timezone.utc)),
        ),
    ]
