# Generated by Django 5.0.4 on 2024-08-12 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0011_rename_receipt_capture_payment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 23, 1, 10, 247857, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 23, 1, 10, 245890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='review_result',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='estado'),
        ),
    ]
