# Generated by Django 5.1 on 2024-09-05 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0012_alter_payment_sending_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='numero telefonico'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(upload_to='', verbose_name='captura de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=50, verbose_name='referencia de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 22, 49, 19, 10675, tzinfo=datetime.timezone.utc), verbose_name='feachade pago'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 22, 49, 19, 8674, tzinfo=datetime.timezone.utc), verbose_name='fecha de subida'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='days_transmit',
            field=models.CharField(max_length=3, verbose_name='dias de transmición'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='publicity',
            field=models.ImageField(upload_to='mavi/static/img', verbose_name='Publicidad'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='publicity_name',
            field=models.CharField(max_length=120, verbose_name='Nombre de Publicidad'),
        ),
        migrations.AlterField(
            model_name='transmissionday',
            name='transmission_day',
            field=models.DateField(verbose_name='dias de trasmición'),
        ),
    ]
