# Generated by Django 5.1 on 2024-09-06 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0013_alter_datauser_phone_alter_payment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(upload_to='payments', verbose_name='captura de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 2, 53, 22, 105628, tzinfo=datetime.timezone.utc), verbose_name='feachade pago'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 2, 53, 22, 89597, tzinfo=datetime.timezone.utc), verbose_name='fecha de subida'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='publicity',
            field=models.ImageField(upload_to='', verbose_name='Publicidad'),
        ),
    ]
