# Generated by Django 5.1 on 2024-09-06 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0014_alter_payment_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='publicity',
            options={'verbose_name': 'Publicidad', 'verbose_name_plural': 'Publicidades'},
        ),
        migrations.AlterModelOptions(
            name='transmissionday',
            options={'verbose_name': "Dia de Trasmición'", 'verbose_name_plural': "Dias de Trasmición'"},
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 3, 43, 25, 551053, tzinfo=datetime.timezone.utc), verbose_name='feachade pago'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 3, 43, 25, 536056, tzinfo=datetime.timezone.utc), verbose_name='fecha de subida'),
        ),
    ]
