# Generated by Django 5.1 on 2024-09-15 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0015_alter_payment_options_alter_publicity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datauser',
            options={'verbose_name': 'Dato de Usuario', 'verbose_name_plural': 'Datos de Usuarios'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='sending_day',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 17, 9, 34, 837570, tzinfo=datetime.timezone.utc), verbose_name='feachade pago'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='contract_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 17, 9, 34, 836533, tzinfo=datetime.timezone.utc), verbose_name='fecha de subida'),
        ),
        migrations.AlterField(
            model_name='publicity',
            name='publicity',
            field=models.ImageField(upload_to='advertisements', verbose_name='Publicidad'),
        ),
    ]
